# Generated by Django 6.0.4 on 2026-04-11 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_registration'),
        ('band_public', '0001_initial'),
        ('scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('type', models.CharField(choices=[('concert', '音樂會'), ('competition', '比賽'), ('recording', '錄音'), ('joint', '聯演')], max_length=20, verbose_name='類型')),
                ('performance_date', models.DateTimeField(verbose_name='演出日期時間')),
                ('status', models.CharField(choices=[('planning', '籌備中'), ('confirmed', '確認'), ('finished', '已結束')], default='planning', max_length=20, verbose_name='狀態')),
                ('performance_venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_events', to='band_public.venue', verbose_name='演出場地')),
            ],
            options={
                'verbose_name': '演出活動',
                'verbose_name_plural': '演出活動列表',
                'ordering': ['-performance_date'],
            },
        ),
        migrations.CreateModel(
            name='GuestMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('from_band', models.CharField(blank=True, max_length=100, verbose_name='來自樂團')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡電話')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.instrumenttype', verbose_name='樂器')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.sectiontype', verbose_name='聲部')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_members', to='events.performanceevent', verbose_name='參與演出')),
            ],
            options={
                'verbose_name': '客座團員',
                'verbose_name_plural': '客座團員列表',
            },
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='第幾次排練')),
                ('date', models.DateTimeField(verbose_name='排練日期時間')),
                ('summary_progress', models.TextField(blank=True, verbose_name='今日進度')),
                ('summary_improve', models.TextField(blank=True, verbose_name='待改進事項')),
                ('summary_next', models.TextField(blank=True, verbose_name='下次排練重點')),
                ('summary_notes', models.TextField(blank=True, verbose_name='給團員備註')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals', to='events.performanceevent', verbose_name='所屬演出活動')),
                ('summary_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsal_summaries', to=settings.AUTH_USER_MODEL, verbose_name='填寫者')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rehearsals', to='band_public.venue', verbose_name='排練場地')),
            ],
            options={
                'verbose_name': '排練',
                'verbose_name_plural': '排練列表',
                'ordering': ['event', 'sequence'],
                'unique_together': {('event', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='RehearsalQRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(verbose_name='到期時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('rehearsal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='events.rehearsal', verbose_name='所屬排練')),
            ],
            options={
                'verbose_name': 'QR Code Token',
                'verbose_name_plural': 'QR Code Token 列表',
            },
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='演出順序')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='events.performanceevent', verbose_name='演出活動')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setlists', to='scores.score', verbose_name='曲目')),
            ],
            options={
                'verbose_name': '演出曲目',
                'verbose_name_plural': '演出曲目列表',
                'ordering': ['event', 'order'],
                'unique_together': {('event', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PartAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_assignments', to='events.guestmember', verbose_name='客座團員')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.instrumenttype', verbose_name='樂器')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_assignments', to=settings.AUTH_USER_MODEL, verbose_name='正式團員')),
                ('score_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parts', to='scores.score', verbose_name='對應分譜')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.sectiontype', verbose_name='聲部')),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_assignments', to='events.setlist', verbose_name='演出曲目')),
            ],
            options={
                'verbose_name': '分譜分配',
                'verbose_name_plural': '分譜分配列表',
            },
        ),
        migrations.CreateModel(
            name='PerformanceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, verbose_name='是否到場')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='確認到場時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_attendances', to=settings.AUTH_USER_MODEL, verbose_name='團員')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.performanceevent', verbose_name='演出活動')),
            ],
            options={
                'verbose_name': '演出出席確認',
                'verbose_name_plural': '演出出席確認列表',
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='請假原因')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '核准'), ('rejected', '拒絕')], default='pending', max_length=10, verbose_name='狀態')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='審核幹部')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='events.rehearsal', verbose_name='排練')),
            ],
            options={
                'verbose_name': '請假申請',
                'verbose_name_plural': '請假申請列表',
                'unique_together': {('member', 'rehearsal')},
            },
        ),
        migrations.CreateModel(
            name='RehearsalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', '出席'), ('leave', '請假'), ('absent', '缺席')], default='absent', max_length=10, verbose_name='狀態')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='簽到時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_attendances', to=settings.AUTH_USER_MODEL, verbose_name='團員')),
                ('rehearsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.rehearsal', verbose_name='排練')),
            ],
            options={
                'verbose_name': '排練出席紀錄',
                'verbose_name_plural': '排練出席紀錄列表',
                'unique_together': {('rehearsal', 'member')},
            },
        ),
    ]
