# Generated by Django 6.0.4 on 2026-04-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_public', '0003_remove_venue_fee_hours_per_session_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevent',
            name='venue_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_events', to='band_public.venuetimeslot', verbose_name='演出時段'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsals', to='band_public.venuetimeslot', verbose_name='時段'),
        ),
    ]
