# Generated by Django 6.0.4 on 2026-04-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_performanceevent_venue_time_slot_rehearsal_time_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performanceevent",
            name="venue_time_slot",
        ),
    ]
