# Generated by Django 6.0.4 on 2026-04-12 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_performanceevent_venue_time_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="申請時間",
            ),
            preserve_default=False,
        ),
    ]
