# Generated by Django 6.0.4 on 2026-05-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_leaverequest_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performanceevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "籌備中"),
                    ("confirmed", "確認"),
                    ("finished", "已結束"),
                    ("cancelled", "已取消"),
                ],
                default="planning",
                max_length=20,
                verbose_name="狀態",
            ),
        ),
    ]
