# Generated by Django 6.0.7 on 2026-08-02 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_leaverequest_result_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partassignment',
            name='guest_member',
        ),
        migrations.AlterField(
            model_name='partassignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_assignments', to=settings.AUTH_USER_MODEL, verbose_name='團員'),
        ),
        migrations.DeleteModel(
            name='GuestMember',
        ),
    ]
