# Generated by Django 6.0.7 on 2026-08-03 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_partassignment_guest_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceattendance',
            name='on_leave',
            field=models.BooleanField(default=False, help_text='演出請假核准後標記為 True，與 confirmed（到場）正交並存', verbose_name='請假'),
        ),
        migrations.CreateModel(
            name='PerformanceLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='請假原因')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '核准'), ('rejected', '拒絕')], default='pending', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('result_seen', models.BooleanField(default=True, help_text='核准/拒絕時設為 False，團員在首頁看到通知後設回 True；預設 True 避免既有資料被當成新結果', verbose_name='團員已讀審核結果')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='events.performanceevent', verbose_name='演出活動')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_performance_leaves', to=settings.AUTH_USER_MODEL, verbose_name='審核幹部')),
            ],
            options={
                'verbose_name': '演出請假申請',
                'verbose_name_plural': '演出請假申請列表',
                'unique_together': {('member', 'event')},
            },
        ),
    ]
