# Generated by Django 6.0.4 on 2026-04-11 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('grad_year', models.PositiveSmallIntegerField(verbose_name='畢業年份')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已拒絕')], default='pending', max_length=10, verbose_name='狀態')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.instrumenttype', verbose_name='樂器')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='審核幹部')),
            ],
            options={
                'verbose_name': '校友報到申請',
                'verbose_name_plural': '校友報到申請列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
