# Generated by Django 6.0.4 on 2026-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='幹部代為建立帳號時設為 True，登入後會被強制導向設定新密碼頁面', verbose_name='需重設密碼'),
        ),
    ]
