# Generated by Django 6.0.7 on 2026-08-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_band',
            field=models.CharField(blank=True, help_text='僅槍手（role=guest）適用', max_length=100, verbose_name='來自樂團'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', '團員'), ('officer', '幹部'), ('admin', '管理員'), ('guest', '槍手')], default='member', max_length=10, verbose_name='角色'),
        ),
    ]
