# Generated by Django 6.1 on 2026-09-07 17:53

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_from_band_alter_user_email_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="住址"),
        ),
        migrations.AddField(
            model_name="registration",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生年月日"),
        ),
        migrations.AddField(
            model_name="registration",
            name="line_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="LINE ID"),
        ),
        migrations.AddField(
            model_name="registration",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[apps.accounts.models.validate_national_id],
                verbose_name="身分證字號",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.sectiontype",
                verbose_name="聲部",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="住址"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生年月日"),
        ),
        migrations.AddField(
            model_name="user",
            name="line_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="LINE ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                help_text="用途為每年的政府名單申報（見 DESIGN 附錄五 #4）",
                max_length=10,
                validators=[apps.accounts.models.validate_national_id],
                verbose_name="身分證字號",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="grad_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="畢業年份"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.instrumenttype",
                verbose_name="樂器",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="手機"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="手機"),
        ),
    ]
