# Generated by Django 6.1 on 2026-09-07 18:57

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


def clear_registration_instrument(apps, schema_editor):
    """把既有申請單的樂器清空，再讓下面的 AlterField 換 FK 指向。

    Registration.instrument 從 InstrumentType（細）改指 InstrumentFamily（族群）時，
    欄位存的還是舊的 InstrumentType id——不清掉的話，那些數字會被當成 InstrumentFamily id
    重新解讀，變成「指向完全不相干的樂器」這種安靜的錯資料。寧可留空讓幹部重填。

    正式環境尚未上線、只有 demo 與測試資料，故直接清空不做對照搬遷。
    """
    apps.get_model('accounts', 'Registration').objects.update(instrument=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_registration_address_registration_birth_date_and_more"),
    ]

    operations = [
        # 順序重要：先清空舊值，再換 FK 指向
        migrations.RunPython(
            clear_registration_instrument, migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name="registration",
            name="alumni_info",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="入學年／科系"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="alumni_info",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="入學年／科系"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.instrumentfamily",
                verbose_name="樂器",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[apps.accounts.models.validate_national_id],
                verbose_name="身分證字號／居留證號",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                help_text="用途為每年的政府名單申報（見 DESIGN 附錄五 #4）",
                max_length=10,
                validators=[apps.accounts.models.validate_national_id],
                verbose_name="身分證字號／居留證號",
            ),
        ),
    ]
