# Generated by Django 6.1 on 2026-09-08 17:36

import apps.accounts.fields
import apps.accounts.models
from django.db import migrations


def encrypt_existing_rows(apps, schema_editor):
    """把既有的明文值就地加密。

    **用原生 SQL 而不是 ORM**：此時欄位已經是 EncryptedTextField，透過 ORM 讀取會嘗試
    解密明文而失敗（回傳空字串），寫回去就會把資料洗掉。原生 SQL 拿到的是欄位原始內容，
    才是這裡要的東西。

    空字串與 NULL 略過——沒有東西要保護，加密只會讓「沒填」看起來像有資料。
    """
    from apps.accounts.fields import encrypt_value

    targets = [
        ('accounts_user', ('national_id', 'address', 'birth_date')),
        ('accounts_registration', ('national_id', 'address', 'birth_date')),
    ]
    with schema_editor.connection.cursor() as cursor:
        for table, columns in targets:
            for column in columns:
                cursor.execute(
                    f'SELECT id, {column} FROM {table} '
                    f"WHERE {column} IS NOT NULL AND {column} <> ''"
                )
                for row_id, plaintext in cursor.fetchall():
                    cursor.execute(
                        f'UPDATE {table} SET {column} = %s WHERE id = %s',
                        [encrypt_value(plaintext), row_id],
                    )


def decrypt_existing_rows(apps, schema_editor):
    """反向：解密回明文，讓這個 migration 可以回退。

    與加密同理走原生 SQL。解不開的值（換過金鑰）留原樣，不清空——
    寧可留下看不懂的密文讓人察覺有異，也不要安靜地把資料變成空的。
    """
    from apps.accounts.fields import decrypt_value

    targets = [
        ('accounts_user', ('national_id', 'address', 'birth_date')),
        ('accounts_registration', ('national_id', 'address', 'birth_date')),
    ]
    with schema_editor.connection.cursor() as cursor:
        for table, columns in targets:
            for column in columns:
                cursor.execute(
                    f'SELECT id, {column} FROM {table} '
                    f"WHERE {column} IS NOT NULL AND {column} <> ''"
                )
                for row_id, ciphertext in cursor.fetchall():
                    plaintext = decrypt_value(ciphertext)
                    if plaintext:
                        cursor.execute(
                            f'UPDATE {table} SET {column} = %s WHERE id = %s',
                            [plaintext, row_id],
                        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_registration_alumni_info_user_alumni_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="address",
            field=apps.accounts.fields.EncryptedTextField(
                blank=True, form_max_length=200, verbose_name="住址"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="birth_date",
            field=apps.accounts.fields.EncryptedDateField(
                blank=True, null=True, verbose_name="出生年月日"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="national_id",
            field=apps.accounts.fields.EncryptedTextField(
                blank=True,
                form_max_length=10,
                validators=[apps.accounts.models.validate_national_id],
                verbose_name="身分證字號／居留證號",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=apps.accounts.fields.EncryptedTextField(
                blank=True, form_max_length=200, verbose_name="住址"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=apps.accounts.fields.EncryptedDateField(
                blank=True, null=True, verbose_name="出生年月日"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=apps.accounts.fields.EncryptedTextField(
                blank=True,
                form_max_length=10,
                help_text="用途為每年的政府名單申報（見 DESIGN 附錄五 #4）",
                validators=[apps.accounts.models.validate_national_id],
                verbose_name="身分證字號／居留證號",
            ),
        ),
        # 順序重要：欄位型別先換成 text，再把既有明文就地加密
        migrations.RunPython(encrypt_existing_rows, decrypt_existing_rows),
    ]
