# Generated by Django 6.1 on 2026-09-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_registration_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "入團申請",
                "verbose_name_plural": "入團申請列表",
            },
        ),
    ]
