# Generated by Django 6.0.4 on 2026-04-11 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('visibility', models.CharField(choices=[('public', '公開'), ('member_only', '團員限定'), ('officer_only', '幹部限定')], default='member_only', max_length=20, verbose_name='可見範圍')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='活動日期')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='發布時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告列表',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
