# Generated by Django 6.0.4 on 2026-04-11 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='類型')),
                ('category', models.CharField(choices=[('venue', '場地費'), ('instructor', '師資費'), ('instrument_purchase', '樂器購置費'), ('instrument_maintenance', '樂器保養費'), ('score', '樂譜費'), ('membership', '會費'), ('other', '其他')], max_length=30, verbose_name='分類')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='金額')),
                ('date', models.DateField(verbose_name='日期')),
                ('description', models.TextField(verbose_name='說明')),
                ('attachment', models.FileField(blank=True, upload_to='finance/', verbose_name='收據掃描檔')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_records', to=settings.AUTH_USER_MODEL, verbose_name='登記者')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='events.performanceevent', verbose_name='關聯演出活動')),
            ],
            options={
                'verbose_name': '財務紀錄',
                'verbose_name_plural': '財務紀錄列表',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50, verbose_name='繳費期別')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='金額')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='繳費日期')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_fees', to=settings.AUTH_USER_MODEL, verbose_name='收款幹部')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_fees', to=settings.AUTH_USER_MODEL, verbose_name='團員')),
            ],
            options={
                'verbose_name': '會費繳納紀錄',
                'verbose_name_plural': '會費繳納紀錄列表',
                'ordering': ['-period', 'member__name'],
                'unique_together': {('member', 'period')},
            },
        ),
    ]
