# Generated by Django 6.0.7 on 2026-08-02 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='金額'),
        ),
    ]
