# Generated by Django 6.0.7 on 2026-08-04 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financerecord_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipfee',
            name='status',
            field=models.CharField(choices=[('unpaid', '應繳未繳'), ('reported', '待確認'), ('paid', '已繳'), ('void', '作廢')], default='unpaid', max_length=10, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='繳費當下自期別金額快照，之後改期別金額不竄改此筆', max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='金額'),
        ),
        migrations.CreateModel(
            name='FeePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年份')),
                ('term', models.CharField(choices=[('first', '上期'), ('second', '下期')], max_length=10, verbose_name='期')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='團費金額')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='繳費開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='繳費截止日')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_periods', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '會費期別',
                'verbose_name_plural': '會費期別列表',
                'ordering': ['-year', 'term'],
                'unique_together': {('year', 'term')},
            },
        ),
        migrations.AddField(
            model_name='membershipfee',
            name='period_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='finance.feeperiod', verbose_name='期別'),
        ),
    ]
