# Generated by Django 6.0.7 on 2026-08-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_swap_period_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipfee',
            name='payment_method',
            field=models.CharField(choices=[('cash', '現金'), ('transfer', '轉帳')], default='cash', max_length=10, verbose_name='繳費方式'),
        ),
        migrations.AddField(
            model_name='membershipfee',
            name='result_seen',
            field=models.BooleanField(default=True, help_text='幹部確認/作廢時設為 False，團員在首頁看到通知後設回 True；預設 True 避免既有資料被當成新結果', verbose_name='團員已讀審核結果'),
        ),
    ]
