# Generated by Django 6.0.7 on 2026-08-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_membershipfee_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipfee',
            name='finance_record',
            field=models.ForeignKey(blank=True, help_text='確認繳費時自動產生的那筆收支明細收入，作廢/退回時連動移除', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_fee', to='finance.financerecord', verbose_name='對應收入紀錄'),
        ),
    ]
