# Generated by Django 6.0.7 on 2026-08-05 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_membershipfee_finance_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.FileField(blank=True, upload_to='payment/', verbose_name='收款 QR Code 圖檔')),
                ('account_info', models.TextField(blank=True, help_text='銀行/分行、戶名、帳號等文字，顯示在申報頁供團員轉帳', verbose_name='轉帳帳號資訊')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '轉帳收款設定',
                'verbose_name_plural': '轉帳收款設定',
            },
        ),
        migrations.AddField(
            model_name='membershipfee',
            name='account_last5',
            field=models.CharField(blank=True, help_text='轉帳繳費時填，供財務對帳；確認後可清除', max_length=5, verbose_name='匯款帳號末五碼'),
        ),
        migrations.AlterField(
            model_name='membershipfee',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_fees', to=settings.AUTH_USER_MODEL, verbose_name='收款幹部（現金）'),
        ),
    ]
