# Generated by Django 6.0.4 on 2026-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_paymentconfig_membershipfee_account_last5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentconfig',
            name='account_info',
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='account_name',
            field=models.CharField(blank=True, default='', help_text='收款帳戶戶名，供團員匯款前確認收款單位', max_length=100, verbose_name='戶名'),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='account_number',
            field=models.CharField(blank=True, default='', help_text='收款帳號；存檔時自動去除 dash 與空白', max_length=30, verbose_name='帳號'),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='bank_code',
            field=models.CharField(blank=True, default='', help_text='轉帳用的金融機構代號，如 004；顯示在申報頁供團員複製', max_length=10, verbose_name='銀行代號'),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='對應銀行名稱，如 臺灣銀行；幹部選代號時自動帶入', max_length=50, verbose_name='銀行名稱'),
        ),
    ]
