# Generated by Django 6.1 on 2026-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_remove_paymentconfig_account_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financerecord",
            name="category",
            field=models.CharField(
                choices=[
                    ("venue", "場地費"),
                    ("instructor", "師資費"),
                    ("instrument_purchase", "樂器購置費"),
                    ("instrument_maintenance", "樂器保養費"),
                    ("score", "樂譜費"),
                    ("insurance", "保險費"),
                    ("membership", "會費"),
                    ("other", "其他"),
                ],
                max_length=30,
                verbose_name="分類",
            ),
        ),
    ]
