# Generated by Django 6.0.4 on 2026-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='場地名稱')),
                ('type', models.CharField(choices=[('performance', '演出場地'), ('rehearsal', '排練場地')], max_length=20, verbose_name='場地類別')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='容納人數')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='場地電話')),
                ('google_map_url', models.URLField(blank=True, verbose_name='Google Maps 網址')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='聯絡人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡人電話')),
                ('transportation', models.TextField(blank=True, verbose_name='交通方式')),
                ('motorcycle_parking', models.CharField(blank=True, choices=[('yes', '可停放'), ('no', '不可停放'), ('limited', '有限制')], max_length=10, verbose_name='機車停放')),
                ('car_parking', models.CharField(blank=True, choices=[('yes', '可停放'), ('no', '不可停放'), ('limited', '有限制')], max_length=10, verbose_name='汽車停放')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '場地',
                'verbose_name_plural': '場地列表',
                'ordering': ['name'],
            },
        ),
    ]
