# Generated by Django 6.0.4 on 2026-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='fee_hours_per_session',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='每次計費小時數'),
        ),
        migrations.AddField(
            model_name='venue',
            name='fee_per_session',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='場地費（每次）'),
        ),
        migrations.AddField(
            model_name='venue',
            name='rehearsal_time',
            field=models.CharField(blank=True, help_text='例：週六 14:00–18:00', max_length=100, verbose_name='團練時間'),
        ),
    ]
