# Generated by Django 6.0.4 on 2026-04-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_public', '0002_venue_fee_hours_per_session_venue_fee_per_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='fee_hours_per_session',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='fee_per_session',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='rehearsal_time',
        ),
        migrations.CreateModel(
            name='VenueTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='例：白天場、夜間場', max_length=50, verbose_name='時段名稱')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('fee', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='費用')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='band_public.venue', verbose_name='場地')),
            ],
            options={
                'verbose_name': '場地時段',
                'verbose_name_plural': '場地時段列表',
                'ordering': ['venue', 'start_time'],
            },
        ),
    ]
