# Generated by Django 6.0.4 on 2026-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_public', '0003_remove_venue_fee_hours_per_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuetimeslot',
            name='label',
        ),
        migrations.AddField(
            model_name='venuetimeslot',
            name='weekday',
            field=models.IntegerField(choices=[(0, '週日'), (1, '週一'), (2, '週二'), (3, '週三'), (4, '週四'), (5, '週五'), (6, '週六')], default=0, verbose_name='星期'),
        ),
    ]
