# Generated by Django 6.0.4 on 2026-04-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_public', '0004_remove_venuetimeslot_label_venuetimeslot_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuetimeslot',
            name='weekday',
        ),
        migrations.AddField(
            model_name='venuetimeslot',
            name='is_fri',
            field=models.BooleanField(default=False, verbose_name='週五'),
        ),
        migrations.AddField(
            model_name='venuetimeslot',
            name='is_mon',
            field=models.BooleanField(default=False, verbose_name='週一'),
        ),
        migrations.AddField(
            model_name='venuetimeslot',
            name='is_sat',
            field=models.BooleanField(default=False, verbose_name='週六'),
        ),
        migrations.AddField(
            model_name='venuetimeslot',
            name='is_sun',
            field=models.BooleanField(default=False, verbose_name='週日'),
        ),
        migrations.AddField(
            model_name='venuetimeslot',
            name='is_thu',
            field=models.BooleanField(default=False, verbose_name='週四'),
        ),
        migrations.AddField(
            model_name='venuetimeslot',
            name='is_tue',
            field=models.BooleanField(default=False, verbose_name='週二'),
        ),
        migrations.AddField(
            model_name='venuetimeslot',
            name='is_wed',
            field=models.BooleanField(default=False, verbose_name='週三'),
        ),
    ]
