# Generated by Django 6.0.4 on 2026-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "band_public",
            "0005_remove_venuetimeslot_weekday_venuetimeslot_is_fri_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="顯示順序"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="公開顯示"),
                ),
            ],
            options={
                "verbose_name": "關於百韻區塊",
                "verbose_name_plural": "關於百韻區塊列表",
                "ordering": ["order", "id"],
            },
        ),
    ]
