# Generated by Django 6.0.4 on 2026-05-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band_public", "0006_aboutsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="章程內容")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最後更新"),
                ),
            ],
            options={
                "verbose_name": "組織章程",
            },
        ),
    ]
