# Generated by Django 6.0.4 on 2026-04-11 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='財產名稱')),
                ('category', models.CharField(choices=[('instrument', '樂器'), ('stand', '譜架'), ('audio', '音響設備'), ('uniform', '制服'), ('other', '其他')], max_length=20, verbose_name='類別')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='購入日期')),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='購入費用')),
                ('condition', models.CharField(choices=[('good', '良好'), ('needs_maintenance', '需保養'), ('in_repair', '送修中')], default='good', max_length=20, verbose_name='狀態')),
                ('storage_location', models.CharField(blank=True, max_length=100, verbose_name='保管位置')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL, verbose_name='負責幹部')),
            ],
            options={
                'verbose_name': '公用財產',
                'verbose_name_plural': '公用財產列表',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateField(verbose_name='借出日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='預計歸還日期')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='實際歸還日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='借用者')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='band_assets.bandproperty', verbose_name='借用財產')),
            ],
            options={
                'verbose_name': '財產借用紀錄',
                'verbose_name_plural': '財產借用紀錄列表',
                'ordering': ['-borrowed_at'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='保養日期')),
                ('description', models.TextField(verbose_name='保養內容')),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='費用')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='band_assets.bandproperty', verbose_name='樂器')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_instruments', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
            ],
            options={
                'verbose_name': '樂器保養紀錄',
                'verbose_name_plural': '樂器保養紀錄列表',
                'ordering': ['-date'],
            },
        ),
    ]
