# Generated by Django 6.0.4 on 2026-04-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_band', models.CharField(max_length=100, verbose_name='對方樂團')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='對方聯絡人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='對方聯絡電話')),
                ('exchange_date', models.DateField(verbose_name='交換日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '樂譜交換',
                'verbose_name_plural': '樂譜交換列表',
                'ordering': ['-exchange_date'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名')),
                ('composer', models.CharField(blank=True, max_length=100, verbose_name='作曲家')),
                ('arranger', models.CharField(blank=True, max_length=100, verbose_name='編曲者')),
                ('score_type', models.CharField(choices=[('full', '總譜'), ('part', '分譜')], max_length=10, verbose_name='譜種')),
                ('copyright_status', models.CharField(choices=[('public_domain', '公版'), ('copyrighted', '有版權'), ('licensed', '已授權')], max_length=20, verbose_name='版權狀態')),
                ('physical_quantity', models.PositiveSmallIntegerField(default=0, verbose_name='實體紙本數量')),
                ('file', models.FileField(blank=True, upload_to='scores/', verbose_name='樂譜 PDF')),
                ('version_note', models.TextField(blank=True, verbose_name='改版說明')),
                ('source', models.CharField(blank=True, choices=[('purchased', '購買'), ('exchange', '與他團交換'), ('donation', '捐贈')], max_length=20, verbose_name='來源')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版商')),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', '初級'), ('intermediate', '中級'), ('advanced', '高級')], max_length=20, verbose_name='難度')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.instrumenttype', verbose_name='樂器')),
                ('parent_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='scores.score', verbose_name='基於版本')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sectiontype', verbose_name='聲部')),
            ],
            options={
                'verbose_name': '樂譜',
                'verbose_name_plural': '樂譜列表',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScoreExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('give', '給出'), ('receive', '收入')], max_length=10, verbose_name='方向')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scores.scoreexchange', verbose_name='交換事件')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_items', to='scores.score', verbose_name='樂譜')),
            ],
            options={
                'verbose_name': '交換明細',
                'verbose_name_plural': '交換明細列表',
            },
        ),
    ]
